INSERT INTO devices (serialNumber, name, brand, vendor, type, osVersionCurrent, osVersionLatest, clsRating, remarks, isCatalog) VALUES
('SN001', 'Pacemaker', 'Brand A', 'Vendor A', 'Type A', '1.0.0', '1.0.1', 4, 'Critical device, requires regular monitoring.', TRUE),
('SN002', 'Blood Pressure Meter', 'Brand B', 'Vendor B', 'Type B', '2.5.3', '2.6.0', 3, 'Battery issues in some units.', TRUE),
('SN003', 'Artificial Heart Valve', 'Brand C', 'Vendor C', 'Type C', '3.1.2', '3.2.0', 4, 'Updated version pending approval.', TRUE),
('SN004', 'Insulin Pump', 'Brand D', 'Vendor D', 'Type D', '1.5.0', '1.5.5', 1, 'Recall due to software bug.', TRUE),
('SN005', 'Ventilator', 'Brand E', 'Vendor E', 'Type E', '2.0.0', '2.1.0', 4, 'High demand during flu season.', TRUE),
('SN006', 'CT Scanner', 'Brand F', 'Vendor F', 'Type F', '4.0.0', '4.2.0', 4, 'Frequent updates required.', TRUE),
('SN007', 'MRI Machine', 'Brand G', 'Vendor G', 'Type G', '5.1.0', '5.3.0', 4, 'High maintenance costs.', TRUE),
('SN008', 'Glucose Monitor', 'Brand H', 'Vendor H', 'Type H', '3.5.0', '3.6.0', 3, 'Software update to improve accuracy.', TRUE),
('SN009', 'Digital Stethoscope', 'Brand I', 'Vendor I', 'Type I', '1.2.0', '1.3.0', 4, 'New model coming next quarter.', TRUE),
('SN010', 'Portable X-ray', 'Brand J', 'Vendor J', 'Type J', '2.8.0', '3.0.0', 4, 'Requires calibration after transport.', TRUE),
('SN011', 'Ultrasound Machine', 'Brand K', 'Vendor K', 'Type K', '2.1.0', '2.2.0', 4, 'Updated software improves image clarity.', TRUE),
('SN012', 'Defibrillator', 'Brand L', 'Vendor L', 'Type L', '1.3.0', '1.3.1', 4, 'Critical for emergency situations.', TRUE),
('SN013', 'ECG Monitor', 'Brand M', 'Vendor M', 'Type M', '3.2.0', '3.2.1', 4, 'Minor display issues reported.', TRUE),
('SN014', 'Oxygen Concentrator', 'Brand N', 'Vendor N', 'Type N', '1.8.0', '1.9.0', 4, 'Important for respiratory care.', TRUE),
('SN015', 'Thermometer', 'Brand O', 'Vendor O', 'Type O', '2.0.0', '2.0.1', 3, 'Occasional inaccuracies in readings.', TRUE),
('SN016', 'Pulse Oximeter', 'Brand P', 'Vendor P', 'Type P', '1.0.0', '1.1.0', 4, 'Crucial for monitoring oxygen levels.', TRUE),
('SN017', 'Nebulizer', 'Brand Q', 'Vendor Q', 'Type Q', '3.0.0', '3.1.0', 3, 'Reported noise issues.', TRUE),
('SN018', 'Heart Rate Monitor', 'Brand R', 'Vendor R', 'Type R', '4.0.0', '4.0.1', 4, 'Stable and reliable device.', TRUE),
('SN019', 'Blood Glucose Meter', 'Brand S', 'Vendor S', 'Type S', '2.5.0', '2.5.1', 3, 'Improvement needed in test strip accuracy.', TRUE),
('SN020', 'Dental X-ray', 'Brand T', 'Vendor T', 'Type T', '1.9.0', '2.0.0', 4, 'Routine updates enhance performance.', TRUE),
('SN021', 'Foetal Doppler', 'Brand U', 'Vendor U', 'Type U', '3.3.0', '3.3.1', 4, 'Used in prenatal care.', TRUE),
('SN022', 'Infusion Pump', 'Brand V', 'Vendor V', 'Type V', '2.7.0', '2.8.0', 1, 'Recall due to dosage errors.', TRUE),
('SN023', 'CPAP Machine', 'Brand W', 'Vendor W', 'Type W', '4.1.0', '4.1.1', 4, 'Vital for sleep apnea treatment.', TRUE),
('SN024', 'Surgical Robot', 'Brand X', 'Vendor X', 'Type X', '5.0.0', '5.1.0', 4, 'High precision in surgical procedures.', TRUE),
('SN025', 'Anaesthesia Machine', 'Brand Y', 'Vendor Y', 'Type Y', '3.4.0', '3.5.0', 3, 'Maintenance needed after each use.', TRUE),
('SN026', 'Dialysis Machine', 'Brand Z', 'Vendor Z', 'Type Z', '4.5.0', '4.5.1', 4, 'Critical for kidney patients.', TRUE),
('SN027', 'BiPAP Machine', 'Brand AA', 'Vendor AA', 'Type AA', '1.6.0', '1.7.0', 3, 'Reports of minor leaks.', TRUE),
('SN028', 'EEG Machine', 'Brand BB', 'Vendor BB', 'Type BB', '2.2.0', '2.2.1', 4, 'Used for brain activity monitoring.', TRUE),
('SN029', 'Audiometer', 'Brand CC', 'Vendor CC', 'Type CC', '3.1.0', '3.2.0', 4, 'Essential for hearing tests.', TRUE),
('SN030', 'Spirometer', 'Brand DD', 'Vendor DD', 'Type DD', '1.0.0', '1.1.0', 3, 'Calibration needed for accurate readings.', TRUE);

INSERT INTO devices (serialNumber, name, brand, vendor, type, osVersionCurrent, osVersionLatest, clsRating, remarks, isCatalog) VALUES
('SN901', 'Pacemaker', 'Brand A', 'Vendor A', 'Type A', '1.0.0', '1.0.1', 4, 'Critical device, requires regular monitoring.', FALSE),
('SN902', 'Blood Pressure Meter', 'Brand B', 'Vendor B', 'Type B', '2.5.3', '2.6.0', 2, 'Battery issues in some units.', FALSE),
('SN903', 'Artificial Heart Valve', 'Brand C', 'Vendor C', 'Type C', '3.1.2', '3.2.0', 3, 'Updated version pending approval.', FALSE);
