import { Column, Device, MedicalHistory } from "./types";

const appName = "Synergy";

export const sampleDevices1: Device[] = [
  {
    serialNumber: "SN001",
    name: "Pacemaker",
    brand: "Brand A",
    vendor: "Vendor A",
    type: "Type A",
    osVersionCurrent: "1.0.0",
    osVersionLatest: "1.0.1",
    clsRating: 4,
    remarks: "Critical device, requires regular monitoring.",
  },
  {
    serialNumber: "SN002",
    name: "Blood Pressure Meter",
    brand: "Brand B",
    vendor: "Vendor B",
    type: "Type B",
    osVersionCurrent: "2.5.3",
    osVersionLatest: "2.6.0",
    clsRating: 2,
    remarks: "Battery issues in some units.",
  },
  {
    serialNumber: "SN003",
    name: "Artificial Heart Valve",
    brand: "Brand C",
    vendor: "Vendor C",
    type: "Type C",
    osVersionCurrent: "3.1.2",
    osVersionLatest: "3.2.0",
    clsRating: 3,
    remarks: "Updated version pending approval.",
  },
];

export const sampleDevices2: Device[] = [
  {
    serialNumber: "SN001",
    name: "Pacemaker",
    brand: "Brand A",
    vendor: "Vendor A",
    type: "Type A",
    osVersionCurrent: "1.0.0",
    osVersionLatest: "1.0.1",
    clsRating: 4,
    remarks: "Critical device, requires regular monitoring.",
  },
  {
    serialNumber: "SN002",
    name: "Blood Pressure Meter",
    brand: "Brand B",
    vendor: "Vendor B",
    type: "Type B",
    osVersionCurrent: "2.5.3",
    osVersionLatest: "2.6.0",
    clsRating: 2,
    remarks: "Battery issues in some units.",
  },
  {
    serialNumber: "SN003",
    name: "Artificial Heart Valve",
    brand: "Brand C",
    vendor: "Vendor C",
    type: "Type C",
    osVersionCurrent: "3.1.2",
    osVersionLatest: "3.2.0",
    clsRating: 3,
    remarks: "Updated version pending approval.",
  },
  {
    serialNumber: "SN004",
    name: "Insulin Pump",
    brand: "Brand D",
    vendor: "Vendor D",
    type: "Type D",
    osVersionCurrent: "1.5.0",
    osVersionLatest: "1.5.5",
    clsRating: 4,
    remarks: "Recall due to software bug.",
  },
  {
    serialNumber: "SN005",
    name: "Ventilator",
    brand: "Brand E",
    vendor: "Vendor E",
    type: "Type E",
    osVersionCurrent: "2.0.0",
    osVersionLatest: "2.1.0",
    clsRating: 5,
    remarks: "High demand during flu season.",
  },
  {
    serialNumber: "SN006",
    name: "CT Scanner",
    brand: "Brand F",
    vendor: "Vendor F",
    type: "Type F",
    osVersionCurrent: "4.0.0",
    osVersionLatest: "4.2.0",
    clsRating: 5,
    remarks: "Frequent updates required.",
  },
  {
    serialNumber: "SN007",
    name: "MRI Machine",
    brand: "Brand G",
    vendor: "Vendor G",
    type: "Type G",
    osVersionCurrent: "5.1.0",
    osVersionLatest: "5.3.0",
    clsRating: 5,
    remarks: "High maintenance costs.",
  },
  {
    serialNumber: "SN008",
    name: "Glucose Monitor",
    brand: "Brand H",
    vendor: "Vendor H",
    type: "Type H",
    osVersionCurrent: "3.5.0",
    osVersionLatest: "3.6.0",
    clsRating: 3,
    remarks: "Software update to improve accuracy.",
  },
  {
    serialNumber: "SN009",
    name: "Digital Stethoscope",
    brand: "Brand I",
    vendor: "Vendor I",
    type: "Type I",
    osVersionCurrent: "1.2.0",
    osVersionLatest: "1.3.0",
    clsRating: 1,
    remarks: "New model coming next quarter.",
  },
  {
    serialNumber: "SN010",
    name: "Portable X-ray",
    brand: "Brand J",
    vendor: "Vendor J",
    type: "Type J",
    osVersionCurrent: "2.8.0",
    osVersionLatest: "3.0.0",
    clsRating: 4,
    remarks: "Requires calibration after transport.",
  },
];

export const sampleDevicesColumns: Column[] = [
  { title: "Device Name", dataIndex: "name", key: "name" },
  { title: "Brand", dataIndex: "brand", key: "brand" },
  { title: "Type", dataIndex: "type", key: "type" },
  { title: "Serial Number", dataIndex: "serialNumber", key: "serialNumber" },
  { title: "CLS Rating", dataIndex: "clsRating", key: "clsRating" },
];

export const sampleMedicalHistory: MedicalHistory[] = [
  {
    id: "1",
    dateCreated: "2024-05-31T10:00:00Z",
    dateAccessed: "2024-05-31T10:05:00Z",
    accessedBy: "Nurse Jane Doe",
    accessLocation: "Terminal A1",
    accessAction: "view",
    bodyPart: "Thorax",
    doctorName: "Dr. Thomas Tiew",
    hospitalName: "Changi General Hospital",
  },
  {
    id: "2",
    dateCreated: "2024-05-30T11:30:00Z",
    dateAccessed: "2024-05-30T11:35:00Z",
    accessedBy: "Doctor Samuel Smith",
    accessLocation: "Terminal A2",
    accessAction: "edit",
    bodyPart: "Brachial",
    doctorName: "Dr. Michael Koey",
    hospitalName: "Tan Tock Seng Hospital",
  },
  {
    id: "3",
    dateCreated: "2024-05-29T09:45:00Z",
    dateAccessed: "2024-05-29T09:50:00Z",
    accessedBy: "Nurse Fatimah Ali",
    accessLocation: "Terminal B1",
    accessAction: "view",
    bodyPart: "Cranial",
    doctorName: "Dr. Jessica Lee",
    hospitalName: "Chong Pang Camp Medical Center",
  },
  {
    id: "4",
    dateCreated: "2024-05-28T14:00:00Z",
    dateAccessed: "2024-05-28T14:05:00Z",
    accessedBy: "Nurse Mika Tan",
    accessLocation: "Terminal C1",
    accessAction: "edit",
    bodyPart: "Abdominal",
    doctorName: "Dr. Lim Hock",
    hospitalName: "Singapore General Hospital",
  },
  {
    id: "5",
    dateCreated: "2024-05-27T15:30:00Z",
    dateAccessed: "2024-05-27T15:35:00Z",
    accessedBy: "Doctor Chang Lee",
    accessLocation: "Terminal D1",
    accessAction: "edit",
    bodyPart: "Pulmonary",
    doctorName: "Dr. Karen Nguyen",
    hospitalName: "Mount Elizabeth Hospital",
  },
  {
    id: "6",
    dateCreated: "2024-05-26T08:45:00Z",
    dateAccessed: "2024-05-26T08:50:00Z",
    accessedBy: "Doctor Rahul Rao",
    accessLocation: "Terminal E1",
    accessAction: "view",
    bodyPart: "Cerebral",
    doctorName: "Dr. Raj Kumar",
    hospitalName: "Khoo Teck Puat Hospital",
  },
  {
    id: "7",
    dateCreated: "2024-05-25T13:15:00Z",
    dateAccessed: "2024-05-25T13:20:00Z",
    accessedBy: "Nurse Susan Loh",
    accessLocation: "Terminal F1",
    accessAction: "view",
    bodyPart: "Cardiac",
    doctorName: "Dr. Prakash Kumar",
    hospitalName: "National University Hospital",
  },
  {
    id: "8",
    dateCreated: "2024-05-24T10:30:00Z",
    dateAccessed: "2024-05-24T10:35:00Z",
    accessedBy: "Nurse Loh Mei",
    accessLocation: "Terminal G1",
    accessAction: "edit",
    bodyPart: "Gastric",
    doctorName: "Dr. Chen Wei",
    hospitalName: "Raffles Hospital",
  },
  {
    id: "9",
    dateCreated: "2024-05-23T12:00:00Z",
    dateAccessed: "2024-05-23T12:05:00Z",
    accessedBy: "Doctor Mei Ling",
    accessLocation: "Terminal H1",
    accessAction: "view",
    bodyPart: "Colonic",
    doctorName: "Dr. Jonathan Tan",
    hospitalName: "Sengkang General Hospital",
  },
  {
    id: "10",
    dateCreated: "2024-05-22T16:45:00Z",
    dateAccessed: "2024-05-22T16:50:00Z",
    accessedBy: "Nurse Kimberly Tan",
    accessLocation: "Terminal I1",
    accessAction: "edit",
    bodyPart: "Dermatological",
    doctorName: "Dr. Hiroshi Sato",
    hospitalName: "Alexandra Hospital",
  }
];


export const sampleHistoryColumns: Column[] = [
  {
    title: "Date",
    dataIndex: "date",
    key: "date",
  },
  {
    title: "Action",
    dataIndex: "accessAction",
    key: "accessAction",
  },
  {
    title: "Accessed By",
    dataIndex: "accessedBy",
    key: "accessedBy",
  },
  {
    title: "Hospital",
    dataIndex: "hospitalName",
    key: "hospitalName",
  },
  {
    title: "Doctor",
    dataIndex: "doctorName",
    key: "doctorName",
  },
  {
    title: "Body Part",
    dataIndex: "bodyPart",
    key: "bodyPart",
  },
];

export default appName;
